### PR TITLE
Fix module loader crash on package.json that doesn't have 'main' property.

### LINKED ISSUE #154: Should throw if `require` failed to load a module
## Code
```js
  var m = require('./a-path-does-not-exist-or-a-bad-module');
  console.log(m);
```
## Expected:
Exception thrown with error:
```
Error: Cannot find module './a-path-does-not-exist-or-a-bad-module'.
```
## Actual:
returns `undefined`

### PR DESCRIPTION
**Pull request by daiyip**
This change fixes #154 and #155.

### CODE REVIEW

File: test/sync-test.ts [hunk 1]
```diff
@@ -79,15 +79,15 @@ describe('napajs/sync', function () {
                 var napa = require('../lib/index');
 
                 napa.store.get('store-for-sync-test-1').set('before-wait', 1);
-                (<any>global).spinWait(100);
+                (<any>global).spinWait(500);
```
Comment (fs-eire) [inline test/sync-test.ts]: The fix of sync-test is already merged into master branch.

Comment (daiyip) [reply test/sync-test.ts]: resolved.
